# ============================================================================
# EZHI Batterie-Regelung Blueprint v1.0.4 - LIGHT
# ============================================================================
# Intelligente Batterie-Steuerung für APsystems EZHI Hybrid-Wechselrichter
# 
# LIGHT VERSION: Nur 1 Helfer nötig (input_datetime.last_peak)
# Alle anderen Werte werden direkt im Blueprint konfiguriert.
#
# CHANGELOG v1.0.4:
# - FIX: Bei WR-Timeout stabilen Aufwach-Wert (-50W) statt 0W setzen
# - NEU: Totband (30W) verhindert Oszillationen bei kleinen Änderungen
# - NEU: Optionaler Batterie-Leistungs-Sensor für Timeout-Erkennung
# - VERBESSERT: Brutto-Überschuss-Berechnung berücksichtigt aktuelle WR-Leistung
#
# INSTALLATION:
# 1. Diese Datei nach /config/blueprints/automation/ezhi/ kopieren
# 2. Einen input_datetime Helfer erstellen: "last_peak" (mit Datum + Zeit)
# 3. In Home Assistant: Einstellungen → Automatisierungen → Blueprint erstellen
# 4. Die 4 Sensoren + 1 Helfer auswählen - fertig!
# ============================================================================

blueprint:
  name: EZHI Batterie-Regelung v1.0.4 LIGHT
  description: |
    Intelligente Nulleinspeisung für APsystems EZHI - **nur 1 Helfer nötig!**
    
    **Features:**
    - 5W-Netzbilanz-Regelung mit Peak-Erkennung
    - Zeitbasierte Peak-Dämpfung und Decay
    - Asymmetrische Rampe (schnell runter, langsam hoch)
    - SOC-Schutz mit PV-Laden (kein Netzladen!)
    - Alle Parameter direkt im Blueprint einstellbar
    
    **v1.0.4 Änderungen:**
    - Bei WR-Timeout: stabiler Aufwach-Wert (-50W) statt 0W
    - Totband (30W) verhindert Oszillationen
    - Verbesserte Brutto-Überschuss-Berechnung
    
    **Benötigt:**
    - APsystems EZHI Integration (kamilkosek/EZHI)
    - Smart Meter mit Netzleistungs-Sensor
    - 1x input_datetime Helfer (last_peak)
    
    **Nicht enthalten (siehe Vollversion):**
    - Solarprognose-Integration
    - Notifications
    - Dashboard-steuerbare Parameter
  domain: automation
  author: Glenbeulah
  
  input:
    # === SENSOREN (4-5 Sensoren + 1 Helfer) ===
    grid_power_sensor:
      name: Netzleistungs-Sensor
      description: "Sensor für Netzleistung in Watt (positiv=Bezug, negativ=Einspeisung)"
      selector:
        entity:
          domain: sensor
          device_class: power
    
    ezhi_on_grid_power:
      name: EZHI On-Grid Power
      description: "number.ezhi_on_grid_power - Sollwert für den Wechselrichter"
      selector:
        entity:
          domain: number
    
    battery_soc_sensor:
      name: Batterie SOC Sensor
      description: "Batterie-Ladestand in Prozent"
      selector:
        entity:
          domain: sensor
          device_class: battery
    
    pv_power_sensor:
      name: PV-Leistungs-Sensor
      description: "Gesamte PV-Produktion in Watt"
      selector:
        entity:
          domain: sensor
          device_class: power
    
    battery_power_sensor:
      name: Batterie-Leistungs-Sensor (Optional)
      description: "Tatsächliche Batterieleistung (für Timeout-Erkennung)"
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: power
    
    # === EINZIGER HELFER ===
    peak_timestamp_helper:
      name: Peak-Zeitstempel Helper
      description: "input_datetime.last_peak - für Peak-Dämpfung (mit Datum + Zeit)"
      selector:
        entity:
          domain: input_datetime
    
    # === BATTERIE-LIMITS ===
    charge_limit:
      name: Lade-Limit
      description: "Maximaler Ladestand in Prozent"
      default: 95
      selector:
        number:
          min: 50
          max: 100
          step: 1
          unit_of_measurement: "%"
    
    discharge_limit:
      name: Entlade-Limit
      description: "Minimaler Ladestand in Prozent"
      default: 20
      selector:
        number:
          min: 5
          max: 50
          step: 1
          unit_of_measurement: "%"
    
    # === REGELUNGSPARAMETER ===
    target_grid_power:
      name: Ziel-Netzbilanz
      description: "Ziel-Wert für Netzleistung (Standard: -10W = leichte Einspeisung)"
      default: -10
      selector:
        number:
          min: -100
          max: 100
          step: 5
          unit_of_measurement: W
    
    buffer_power:
      name: Netzbilanz-Puffer
      description: "Toleranz-Zone um den Zielwert (keine Regelung innerhalb)"
      default: 100
      selector:
        number:
          min: 20
          max: 500
          step: 10
          unit_of_measurement: W
    
    min_inverter_power:
      name: Max. Ladeleistung
      description: "Maximale Ladeleistung (negativer Wert)"
      default: -1200
      selector:
        number:
          min: -3000
          max: 0
          step: 100
          unit_of_measurement: W
    
    max_inverter_power:
      name: Max. Entladeleistung
      description: "Maximale Entladeleistung (positiver Wert)"
      default: 1200
      selector:
        number:
          min: 0
          max: 3000
          step: 100
          unit_of_measurement: W
    
    # === PEAK-ERKENNUNG ===
    peak_threshold_low:
      name: Peak-Schwelle Niedrig
      description: "Ab dieser Netzlast: moderate Reaktion (Faktor 0.6)"
      default: 200
      selector:
        number:
          min: 50
          max: 500
          step: 25
          unit_of_measurement: W
    
    peak_threshold_high:
      name: Peak-Schwelle Hoch
      description: "Ab dieser Netzlast: verstärkte Reaktion (Faktor 1.0)"
      default: 600
      selector:
        number:
          min: 200
          max: 1500
          step: 50
          unit_of_measurement: W

# ============================================================================
# TRIGGER
# ============================================================================
trigger:
  - platform: state
    entity_id: !input grid_power_sensor

# ============================================================================
# BEDINGUNG: Mindestabstand zwischen Ausführungen (0.3s)
# ============================================================================
condition:
  - condition: template
    value_template: >
      {% set last = this.attributes.last_triggered | default(0, true) %}
      {{ (as_timestamp(now()) - (as_timestamp(last) | float(0))) > 0.3 }}

# ============================================================================
# VARIABLEN
# ============================================================================
variables:
  # Input-Referenzen
  grid_sensor: !input grid_power_sensor
  wr_number: !input ezhi_on_grid_power
  soc_sensor: !input battery_soc_sensor
  pv_sensor: !input pv_power_sensor
  batt_power_sensor: !input battery_power_sensor
  peak_time_input: !input peak_timestamp_helper
  
  # Blueprint-Parameter
  lade_limit: !input charge_limit
  entlade_limit: !input discharge_limit
  sollwert: !input target_grid_power
  puffer: !input buffer_power
  min_inverter: !input min_inverter_power
  max_inverter: !input max_inverter_power
  peak_schwelle_niedrig: !input peak_threshold_low
  peak_schwelle_hoch: !input peak_threshold_high
  
  # Sensor-Werte
  istwert: "{{ states(grid_sensor) | float(0) }}"
  aktuell: "{{ states(wr_number) | float(0) }}"
  soc: "{{ states(soc_sensor) | float(0) }}"
  pv_power: "{{ states(pv_sensor) | float(0) }}"
  wr_istwert: >
    {% if batt_power_sensor %}
      {{ states(batt_power_sensor) | float(0) }}
    {% else %}
      {{ aktuell }}
    {% endif %}
  wr_im_timeout: "{{ batt_power_sensor and (aktuell | abs) > 50 and (wr_istwert | abs) < 10 }}"
  
  # SOC-Schutz Parameter (v1.0.4)
  soc_schutz_puffer: 70
  soc_schutz_rampe: 40
  soc_schutz_min_ladung: 30
  soc_schutz_totband: 30
  soc_schutz_aufwach_wert: -50
  
  # SOC-Schutz Ladewert-Berechnung (v1.0.4)
  soc_schutz_ladewert: |
    {# === TIMEOUT-SCHUTZ (v1.0.4) === #}
    {% if wr_im_timeout %}
      {{ soc_schutz_aufwach_wert }}
    {% elif pv_power > 10 and istwert < -30 %}
      {# === PV-LADEN MÖGLICH === #}
      {% set ueberschuss = istwert | float %}
      {# Brutto-Überschuss: Netz + was WR bereits lädt #}
      {% set ziel = ueberschuss - wr_istwert + soc_schutz_puffer %}
      
      {% if ziel < min_inverter %}
        {% set ziel = min_inverter %}
      {% endif %}
      {% if ziel > -soc_schutz_min_ladung %}
        {% set ziel = -soc_schutz_min_ladung %}
      {% endif %}
      
      {# === TOTBAND: Nur ändern wenn Differenz > 30W === #}
      {% set differenz = (aktuell - ziel) | abs %}
      {% if differenz < soc_schutz_totband %}
        {{ aktuell | round(0) }}
      {% elif aktuell > ziel %}
        {% set neuer_wert = aktuell - soc_schutz_rampe %}
        {% if neuer_wert < ziel %}
          {% set neuer_wert = ziel %}
        {% endif %}
        {{ neuer_wert | round(0) }}
      {% else %}
        {{ ziel | round(0) }}
      {% endif %}
    {% else %}
      0
    {% endif %}
  
  # Peak-Erkennung
  peak_level: |
    {% if istwert > peak_schwelle_hoch %}
      2
    {% elif istwert > peak_schwelle_niedrig %}
      1
    {% else %}
      0
    {% endif %}
  
  # Regelungsfaktoren (fest)
  faktor_basis: 0.25
  faktor_peak_klein: 0.6
  faktor_peak_gross: 1.0
  
  # Zeitbasierte Peak-Dämpfung
  last_peak: "{{ states(peak_time_input) | as_timestamp | default(0) | float(0) }}"
  time_since_peak: "{{ as_timestamp(now()) - last_peak }}"
  
  post_peak_damping: |
    {% set t = time_since_peak %}
    {% if t < 15 %}
      0.4
    {% elif t < 45 %}
      0.7
    {% elif t < 90 %}
      0.9
    {% else %}
      1.0
    {% endif %}
  
  # Exponentieller Decay
  tau: 45
  decay: |
    {% set t = time_since_peak %}
    {% if t > 120 %}
      1.0
    {% else %}
      {{ (2.718281828459045 ** (-t/tau)) | float }}
    {% endif %}
  
  # Faktor mit Dämpfung
  faktor: >
    {% set level = peak_level | int %}
    {% set base_factor = faktor_peak_gross if level == 2 else (faktor_peak_klein if level == 1 else faktor_basis) %}
    {{ (base_factor * post_peak_damping) | float }}
  
  # Delta-Berechnung mit Begrenzung und Decay
  delta: |
    {% set raw = (istwert | float) * (faktor | float) %}
    {% set max_delta = 600 %}
    {% if raw > max_delta %}
      {{ max_delta }}
    {% elif raw < -max_delta %}
      {{ -max_delta }}
    {% else %}
      {{ raw | round(0) }}
    {% endif %}
  
  # Neuer WR-Sollwert mit Decay
  new_value: |
    {% set target = (aktuell | float) + ((delta | float) * (decay | float)) %}
    {% if target > max_inverter %}
      {{ max_inverter }}
    {% elif target < min_inverter %}
      {{ min_inverter }}
    {% else %}
      {{ target | round(0) }}
    {% endif %}

# ============================================================================
# AKTIONEN
# ============================================================================
action:
  - choose:
      # === SOC-SCHUTZ ===
      - conditions:
          - condition: template
            value_template: "{{ soc <= entlade_limit }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input ezhi_on_grid_power
            data:
              value: "{{ soc_schutz_ladewert }}"
          - stop: ""
    
    # === NORMALE REGELUNG ===
    default:
      # Nur regeln wenn außerhalb Puffer-Zone
      - condition: template
        value_template: "{{ (istwert > (sollwert + puffer) or istwert < (sollwert - puffer)) }}"
      
      # WR-Sollwert setzen
      - service: number.set_value
        target:
          entity_id: !input ezhi_on_grid_power
        data:
          value: "{{ new_value }}"
      
      # Peak-Timestamp aktualisieren
      - if:
          - condition: template
            value_template: "{{ peak_level > 0 and (last_peak == 0 or time_since_peak > 30) }}"
        then:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input peak_timestamp_helper
            data:
              timestamp: "{{ as_timestamp(now()) }}"

mode: single
max_exceeded: silent
